= SUSE Linux Enterprise Server for SAP Applications Documentation

This is the source for the official SUSE Linux Enterprise Server for
SAP Applications documentation. 

This repository hosts the documentation sources including translations (if
available).

Released versions of the documentation are published at
https://documentation.suse.com/sles-sap/.


== Editing DocBook

To contribute to the documentation, you need to write DocBook.

* You can learn about DocBook syntax at http://docbook.org/tdg5/en/html .
* SUSE documents are generally built with DAPS (package `daps`) and the
  SUSE XSL Stylesheets (package `suse-xsl-stylesheets`). Ideally, you should
  get these from the repository `Documentation:Tools`. However, slightly
  older versions are also available from the SLE and openSUSE repositories.
* Basic daps usage:
** `$ daps -d DC-<YOUR_BOOK> validate`: Make sure what you have written is
    well-formed XML and valid DocBook 5
** `$ daps -d DC-<YOUR_BOOK> pdf`: Build a PDF document
** `$ daps -d DC-<YOUR_BOOK> html`: Build muliti-page HTML document
** Learn more at https://opensuse.github.io/daps
